### ISSUE TITLE
Bug: python2.7 + mac os 에서 chatter.py 구문 오류 

### ISSUE THREAD

**Issue by zoomer75** [JungWinter/chatterbox#7]
- OS: mac os sierra
- Python 버전: 2.7
- Chatterbox 버전: chatterbox.py-0.2.1

flask 예제를 실행하니 File "/Users/round/PycharmProjects/dkitBot/venv/lib/python2.7/site-packages/chatterbox/chatter.py", line 10
    memory: str = 'dict',
          ^
SyntaxError: invalid syntax

이라고 발생이 됩니다.

**Comment by JungWinter** [comment]
현재 `chatterbox`는 파이썬 >=3.4 버전만 지원하고 있습니다! python 2.7 환경에서는 pypi로 설치가 안되게 해놨어야했는데 제가 놓쳤네요.
